// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using TaskManagement.Infraestructure.Persistence.Context;

#nullable disable

namespace TaskManagement.Infraestructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskManagement.Core.Domain.Entities.TaskStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("IsActive")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TaskStatus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 6, 2, 21, 52, 0, 685, DateTimeKind.Local).AddTicks(9008),
                            IsActive = 1,
                            ModifiedBy = "N/A",
                            ModifiedDate = new DateTime(2024, 6, 2, 21, 52, 0, 685, DateTimeKind.Local).AddTicks(9049),
                            Name = "Nueva"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 6, 2, 21, 52, 0, 685, DateTimeKind.Local).AddTicks(9053),
                            IsActive = 1,
                            ModifiedBy = "N/A",
                            ModifiedDate = new DateTime(2024, 6, 2, 21, 52, 0, 685, DateTimeKind.Local).AddTicks(9054),
                            Name = "En proceso"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 6, 2, 21, 52, 0, 685, DateTimeKind.Local).AddTicks(9057),
                            IsActive = 1,
                            ModifiedBy = "N/A",
                            ModifiedDate = new DateTime(2024, 6, 2, 21, 52, 0, 685, DateTimeKind.Local).AddTicks(9058),
                            Name = "Completada"
                        });
                });

            modelBuilder.Entity("TaskManagement.Core.Domain.Entities.Tasks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("IdTaskStatus")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("IsActive")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR2(60)");

                    b.HasKey("Id");

                    b.HasIndex("IdTaskStatus");

                    b.ToTable("Task", (string)null);
                });

            modelBuilder.Entity("TaskManagement.Core.Domain.Entities.Tasks", b =>
                {
                    b.HasOne("TaskManagement.Core.Domain.Entities.TaskStatus", "TaskStatus")
                        .WithMany("Tasks")
                        .HasForeignKey("IdTaskStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskStatus");
                });

            modelBuilder.Entity("TaskManagement.Core.Domain.Entities.TaskStatus", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
